### ISSUE TITLE
syntax error: operand expected

### ISSUE THREAD

**Issue by gunqqer** [dylanaraps/pxltrm#1]
When trying to run this I get 
```
gunqqer@Friithian:~$ ~/Documents/pxltrm/pxltrm 

/home/gunqqer/Documents/pxltrm/pxltrm: line 29: "130" / 24: syntax error: operand expected (error token is ""130" / 24")
```
I am running GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

**Comment by lmintmate** [comment]
Same here. My error message says (after a screenful of blank space):
`/home/lmintmate/bin/pxltrm: line 29: "84" / 24: syntax error: operand expected`
I'm normally running zsh 5.1.1 (x86_64-ubuntu-linux-gnu), but I also got the same error on GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu).
The concept of this program looks pretty interesting, and, even though I'm not a very heavy terminal user, I was still intrigued by the concept upon seeing it on r/unixporn - kudos. Thanks in advance for any help in getting it to work.

**Comment by dylanaraps** [comment]
Fixed.
