### ISSUE TITLE
doesn't work on OSX

### ISSUE THREAD

**Issue by cmhrpr** [dylanaraps/pxltrm#2]
```bash
./pxltrm: line 29: "80" / 24: syntax error: operand expected (error token is ""8
```

**Comment by bsnyde** [comment]
Same here.

**Comment by msmahon** [comment]
It works if you remove the quotes around `"${COLUMNS:=80}"` on line 29. Then on line 146 you have to change `-N` to `-n`

**Comment by lmintmate** [comment]
Thank you very much @msmahon! This got it to work for me! (and to figure that I posted in the other, older, thread reporting the same issue first...)

**Comment by cmhrpr** [comment]
@msmahon Thanks a lot!
