### ISSUE TITLE
Blank or "black" spots when rendering with cat or reopening a file with pxltrm

### ISSUE THREAD

**Issue by TheOuterLinux** [dylanaraps/pxltrm#9]
Blank or "black" spots tend to show up when cating the saved image or reopening it with pxltrm. It's either that different colors don't like to touch or it's going back over a color with a different color that's doing it.

**Comment by dylanaraps** [comment]
I can reproduce this. I just need to figure out why this is happening.

**Comment by dylanaraps** [comment]
Try the latest commit (you'll need to make a new image). I think I fixed this.

**Comment by dylanaraps** [comment]
This has been fixed.
